
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("932x626")
window.configure(bg = "#E8E8E8")


canvasListSuburb = Canvas(
    window,
    bg = "#E8E8E8",
    height = 626,
    width = 932,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvasListSuburb.place(x = 0, y = 0)
canvasListSuburb.create_rectangle(
    228.0,
    122.0,
    899.0,
    517.0,
    fill="#FFFFFF",
    outline="")

canvasListSuburb.create_rectangle(
    0.0,
    0.0,
    195.0,
    626.0,
    fill="#32213A",
    outline="")


canvasListSuburb.create_text(
    56.0,
    36.0,
    anchor="nw",
    text="AJJ",
    fill="#FFFFFF",
    font=("Inter Bold", 40 * -1)
)

image_image_2 = PhotoImage(
    file=relative_to_assets("home.png"))
image_2 = canvasListSuburb.create_image(
    96.0,
    145.0,
    image=image_image_2
)

image_image_1 = PhotoImage(
    file=relative_to_assets("display_listings_for_suburb_img.png"))
image_1 = canvasListSuburb.create_image(
    564.0,
    70.0,
    image=image_image_1
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvasListSuburb.create_image(
    354.5,
    475.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=269.0,
    y=455.0,
    width=171.0,
    height=38.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvasListSuburb.create_image(
    781.0,
    474.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=672.0,
    y=454.0,
    width=218.0,
    height=38.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvasListSuburb.create_image(
    547.5,
    474.0,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=462.0,
    y=454.0,
    width=171.0,
    height=38.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("display.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=454.0,
    y=536.0,
    width=218.0,
    height=39.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("display_by_ratings.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=33.0,
    y=539.0,
    width=126.0,
    height=56.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("price_chart.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=33.0,
    y=302.0,
    width=126.0,
    height=56.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("cleanliness.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=33.0,
    y=460.0,
    width=126.0,
    height=56.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("search.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=33.0,
    y=381.0,
    width=126.0,
    height=56.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("suburb_listing.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=34.0,
    y=223.0,
    width=126.0,
    height=56.0
)
window.resizable(False, False)
window.mainloop()
