# List of keywords for cleanliness
cleanlinesskeywords = [
    'dirty',
    'clean',
    'cleanliness',
    'disgusting',
    'disgust',
    'mold',
    'neat',
    'filthy',
    'fresh',
    'spotless',
    'dust',
    'germ',
    'immaculate',
    'tidy',
    'hygiene',
    'hygenic',
    'gleaming'
    'unsoiled',
    'sanitary',
    'contaminated'
    'mop',
    'vacuum'
    'decontaminate',
    'orderly',
    'rinse',
    'cob',
    'cobwebs',
    'rodents',
    'rodent',
    'vermin',
    'mice',
    'mouse'
]
