
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, Frame
from PIL import Image,ImageTk


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()
window.title("AJJ BNB")

window.configure(bg = "#E8E8E8")

window_height = 626
window_width = 932

def center_screen():
    """ gets the coordinates of the center of the screen """
    global screen_height, screen_width, x_cordinate, y_cordinate

    screen_width = window.winfo_screenwidth()
    screen_height = window.winfo_screenheight()
        # Coordinates of the upper left corner of the window to make the window appear in the center
    x_cordinate = int((screen_width/2) - (window_width/2))
    y_cordinate = int((screen_height/2) - (window_height/2))
    window.geometry("{}x{}+{}+{}".format(window_width, window_height, x_cordinate, y_cordinate))

center_screen()
    
photo_images = {}
current_canvas = None

#Display suburb listing
def show_canvas2():
    print('canvas 2')
    canvas.pack_forget()
    global current_canvas
    
    if current_canvas:
        current_canvas.pack_forget()
        
    canvasListSuburb = Canvas(
    window,
    bg = "#E8E8E8",
    height = 626,
    width = 932,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
    )

    canvasListSuburb.place(x = 0, y = 0)
    canvasListSuburb.update()  # Update the canvas before getting dimensions
    print("Canvas dimensions:", canvasListSuburb.winfo_width(), canvasListSuburb.winfo_height())

    canvasListSuburb.create_rectangle(
        228.0,
        122.0,
        899.0,
        517.0,
        fill="#FFFFFF",
        outline="")

    canvasListSuburb.create_rectangle(
        0.0,
        0.0,
        195.0,
        626.0,
        fill="#32213A",
        outline="")

    canvasListSuburb.create_text(
        56.0,
        36.0,
        anchor="nw",
        text="AJJ",
        fill="#FFFFFF",
        font=("Inter Bold", 40 * -1)
    )

    image_image_6 = PhotoImage(
        file=relative_to_assets("home.png"))
    window.one = image_image_6
    # Create and place the image on canvasListSuburb
    image_6 = canvasListSuburb.create_image(
        96.0,
        145.0,
        image=image_image_6
    )
    button_image_1 = PhotoImage(
        file=relative_to_assets("display.png"))
    window.negative = button_image_1
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_1 clicked"),
        relief="flat"
    )
    button_1.place(
        x=454.0,
        y=536.0,
        width=218.0,
        height=39.0
    )
    image_image_7 = PhotoImage(
        file=relative_to_assets("display_listings_for_suburb_img.png"))
    window.two = image_image_7
    image_7 = canvasListSuburb.create_image(
        564.0,
        70.0,
        image=image_image_7
    )

    entry_image_1 = PhotoImage(
        file=relative_to_assets("entry_1.png"))
    window.three = entry_image_1
    entry_bg_1 = canvasListSuburb.create_image(
        354.5,
        475.0,
        image=entry_image_1
    )
    entry_1 = Entry(
        bd=0,
        bg="#D9D9D9",
        fg="#000716",
        highlightthickness=0
    )
    entry_1.place(
    x=269.0,
    y=455.0,
    width=171.0,
    height=38.0
    )
    
    entry_image_2 = PhotoImage(
        file=relative_to_assets("entry_2.png"))
    window.four = entry_image_2
    entry_bg_2 = canvasListSuburb.create_image(
        781.0,
        474.0,
        image=entry_image_2
    )
    entry_2 = Entry(
        bd=0,
        bg="#D9D9D9",
        fg="#000716",
        highlightthickness=0
    )
    
    entry_2.place(
        x=672.0,
        y=454.0,
        width=218.0,
        height=38.0
    )
    
    entry_image_3 = PhotoImage(
        file=relative_to_assets("entry_3.png"))
    window.five = entry_image_3
    entry_bg_3 = canvasListSuburb.create_image(
        547.5,
        474.0,
        image=entry_image_3
    )
    entry_3 = Entry(
        bd=0,
        bg="#D9D9D9",
        fg="#000716",
        highlightthickness=0
    )
    
    entry_3.place(
    x=462.0,
    y=454.0,
    width=171.0,
    height=38.0
    )

    button_image_1 = PhotoImage(
    file=relative_to_assets("display_by_ratings.png"))
    window.six = button_image_1
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: show_canvas6(),
        relief="flat"
    )
    button_1.place(
        x=33.0,
        y=539.0,
        width=126.0,
        height=56.0
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets("price_chart.png"))
    window.seven = button_image_2
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: show_canvas4(),
        relief="flat"
    )
    button_2.place(
        x=33.0,
        y=302.0,
        width=126.0,
        height=56.0
    )

    button_image_3 = PhotoImage(
        file=relative_to_assets("cleanliness.png"))
    window.eight = button_image_3
    button_3 = Button(
        image=button_image_3,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: show_canvas3(),
        relief="flat"
    )
    button_3.place(
        x=33.0,
        y=460.0,
        width=126.0,
        height=56.0
    )

    button_image_4 = PhotoImage(
        file=relative_to_assets("search.png"))
    window.nine = button_image_4
    button_4 = Button(
        image=button_image_4,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: show_canvas5(),
        relief="flat"
    )
    button_4.place(
        x=33.0,
        y=381.0,
        width=126.0,
        height=56.0
    )

    button_image_5 = PhotoImage(
        file=relative_to_assets("suburb_listing.png"))
    window.ten = button_image_5
    button_5 = Button(
        image=button_image_5,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: show_canvas2(),
        relief="flat"
    )
    button_5.place(
        x=33.0,
        y=223.0,
        width=126.0,
        height=56.0
    )

    canvasListSuburb.create_text(
        56.0,
        36.0,
        anchor="nw",
        text="AJJ",
        fill="#FFFFFF",
        font=("Inter Bold", 40 * -1)
    )

    canvasListSuburb.pack()
    current_canvas = canvasListSuburb


#Display Price Listings function
def show_canvas4():
    print("canvas4")
    canvas.pack_forget()
    global current_canvas
    
    if current_canvas:
        current_canvas.pack_forget()
        
    canvasPriceListings = Canvas(
    window,
    bg = "#E8E8E8",
    height = 626,
    width = 932,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
    )

    canvasPriceListings.place(x = 0, y = 0)
    canvasPriceListings.update()  # Update the canvas before getting dimensions
    print("Canvas dimensions:", canvasPriceListings.winfo_width(), canvasPriceListings.winfo_height())

    canvasPriceListings.create_rectangle(
        228.0,
        122.0,
        899.0,
        517.0,
        fill="#FFFFFF",
        outline="")

    canvasPriceListings.create_rectangle(
        0.0,
        0.0,
        195.0,
        626.0,
        fill="#32213A",
        outline="")

    canvasPriceListings.create_text(
        56.0,
        36.0,
        anchor="nw",
        text="AJJ",
        fill="#FFFFFF",
        font=("Inter Bold", 40 * -1)
    )

    image_image_6 = PhotoImage(
        file=relative_to_assets("home.png"))
    window.one = image_image_6
    # Create and place the image on canvasPriceListings
    image_6 = canvasPriceListings.create_image(
        96.0,
        145.0,
        image=image_image_6
    )
    button_image_1 = PhotoImage(
        file=relative_to_assets("display.png"))
    window.negative = button_image_1
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_1 clicked"),
        relief="flat"
    )
    button_1.place(
        x=454.0,
        y=536.0,
        width=218.0,
        height=39.0
    )
    image_image_7 = PhotoImage(
        file=relative_to_assets("display_listings_for_suburb_img.png"))
    window.two = image_image_7
    image_7 = canvasPriceListings.create_image(
        564.0,
        70.0,
        image=image_image_7
    )
    
    image_image_1 = PhotoImage(
    file=relative_to_assets("display_price_distribution.png"))
    window.two = image_image_1
    image_1 = canvasPriceListings.create_image(
        564.0,
        70.0,
        image=image_image_1
    )
    
    entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
    window.three = entry_image_1
    entry_bg_1 = canvasPriceListings.create_image(
        544.5,
        474.5,
        image=entry_image_1
    )
    
    entry_1 = Entry(
        bd=0,
        bg="#E8E8E8",
        fg="#000716",
        highlightthickness=0
    )
    entry_1.place(
        x=459.0,
        y=455.0,
        width=171.0,
        height=37.0
    )

    entry_image_2 = PhotoImage(
        file=relative_to_assets("entry_3.png"))
    window.four = entry_image_2
    entry_bg_2 = canvasPriceListings.create_image(
        351.5,
        474.5,
        image=entry_image_2
    )
    entry_2 = Entry(
        bd=0,
        bg="#E8E8E8",
        fg="#000716",
        highlightthickness=0
    )
    entry_2.place(
        x=266.0,
        y=455.0,
        width=171.0,
        height=37.0
    )

    entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_5.png"))
    window.five = entry_image_3
    entry_bg_3 = canvasPriceListings.create_image(
        778.0,
        474.5,
        image=entry_image_3
    )
    entry_3 = Entry(
        bd=0,
        bg="#E8E8E8",
        fg="#000716",
        highlightthickness=0
    )
    entry_3.place(
        x=669.0,
        y=455.0,
        width=218.0,
        height=37.0
    )
    
    button_image_1 = PhotoImage(
    file=relative_to_assets("display_by_ratings.png"))
    window.six = button_image_1
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: show_canvas6(),
        relief="flat"
    )
    button_1.place(
        x=33.0,
        y=539.0,
        width=126.0,
        height=56.0
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets("price_chart.png"))
    window.seven = button_image_2
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: show_canvas4(),
        relief="flat"
    )
    button_2.place(
        x=33.0,
        y=302.0,
        width=126.0,
        height=56.0
    )

    button_image_3 = PhotoImage(
        file=relative_to_assets("cleanliness.png"))
    window.eight = button_image_3
    button_3 = Button(
        image=button_image_3,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: show_canvas3(),
        relief="flat"
    )
    button_3.place(
        x=33.0,
        y=460.0,
        width=126.0,
        height=56.0
    )

    button_image_4 = PhotoImage(
        file=relative_to_assets("search.png"))
    window.nine = button_image_4
    button_4 = Button(
        image=button_image_4,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: show_canvas5(),
        relief="flat"
    )
    button_4.place(
        x=33.0,
        y=381.0,
        width=126.0,
        height=56.0
    )

    button_image_5 = PhotoImage(
        file=relative_to_assets("suburb_listing.png"))
    window.ten = button_image_5
    button_5 = Button(
        image=button_image_5,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: show_canvas2(),
        relief="flat"
    )
    button_5.place(
        x=33.0,
        y=223.0,
        width=126.0,
        height=56.0
    )

    canvasPriceListings.create_text(
        56.0,
        36.0,
        anchor="nw",
        text="AJJ",
        fill="#FFFFFF",
        font=("Inter Bold", 40 * -1)
    )

    canvasPriceListings.pack()
    current_canvas = canvasPriceListings
    
    
#Display search records function (Search button)
def show_canvas5():
    print("canvas5")
    canvas.pack_forget()
    global current_canvas
    
    if current_canvas:
        current_canvas.pack_forget()
        
    canvasSearch = Canvas(
    window,
    bg = "#E8E8E8",
    height = 626,
    width = 932,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
    )

    canvasSearch.place(x = 0, y = 0)
    canvasSearch.update()  # Update the canvas before getting dimensions
    print("Canvas dimensions:", canvasSearch.winfo_width(), canvasSearch.winfo_height())

    canvasSearch.create_rectangle(
        228.0,
        122.0,
        899.0,
        517.0,
        fill="#FFFFFF",
        outline="")

    canvasSearch.create_rectangle(
        0.0,
        0.0,
        195.0,
        626.0,
        fill="#32213A",
        outline="")

    canvasSearch.create_text(
        56.0,
        36.0,
        anchor="nw",
        text="AJJ",
        fill="#FFFFFF",
        font=("Inter Bold", 40 * -1)
    )

    image_image_6 = PhotoImage(
        file=relative_to_assets("home.png"))
    window.one = image_image_6
    # Create and place the image on canvasSearch
    image_6 = canvasSearch.create_image(
        96.0,
        145.0,
        image=image_image_6
    )
    button_image_1 = PhotoImage(
        file=relative_to_assets("display.png"))
    window.negative = button_image_1
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_1 clicked"),
        relief="flat"
    )
    button_1.place(
        x=454.0,
        y=536.0,
        width=218.0,
        height=39.0
    )

    image_image_1 = PhotoImage(
    file=relative_to_assets("Display_Search_Records.png"))
    window.two = image_image_1
    image_1 = canvasSearch.create_image(
        564.0,
        70.0,
        image=image_image_1
    )
    
    entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
    window.three = entry_image_1
    entry_bg_1 = canvasSearch.create_image(
        563.5,
        474.5,
        image=entry_image_1
    )
    entry_1 = Entry(
        bd=0,
        bg="#E8E8E8",
        fg="#000716",
        highlightthickness=0
    )
    entry_1.place(
        x=446.0,
        y=455.0,
        width=235.0,
        height=37.0
    )
    
    button_image_1 = PhotoImage(
    file=relative_to_assets("display_by_ratings.png"))
    window.six = button_image_1
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: show_canvas6(),
        relief="flat"
    )
    button_1.place(
        x=33.0,
        y=539.0,
        width=126.0,
        height=56.0
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets("price_chart.png"))
    window.seven = button_image_2
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: show_canvas4(),
        relief="flat"
    )
    button_2.place(
        x=33.0,
        y=302.0,
        width=126.0,
        height=56.0
    )

    button_image_3 = PhotoImage(
        file=relative_to_assets("cleanliness.png"))
    window.eight = button_image_3
    button_3 = Button(
        image=button_image_3,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: show_canvas3(),
        relief="flat"
    )
    button_3.place(
        x=33.0,
        y=460.0,
        width=126.0,
        height=56.0
    )

    button_image_4 = PhotoImage(
        file=relative_to_assets("search.png"))
    window.nine = button_image_4
    button_4 = Button(
        image=button_image_4,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: show_canvas5(),
        relief="flat"
    )
    button_4.place(
        x=33.0,
        y=381.0,
        width=126.0,
        height=56.0
    )

    button_image_5 = PhotoImage(
        file=relative_to_assets("suburb_listing.png"))
    window.ten = button_image_5
    button_5 = Button(
        image=button_image_5,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: show_canvas2(),
        relief="flat"
    )
    button_5.place(
        x=33.0,
        y=223.0,
        width=126.0,
        height=56.0
    )

    canvasSearch.create_text(
        56.0,
        36.0,
        anchor="nw",
        text="AJJ",
        fill="#FFFFFF",
        font=("Inter Bold", 40 * -1)
    )

    canvasSearch.pack()
    current_canvas = canvasSearch
    
    
#Display cleanliness function
def show_canvas3():
    print('canvas 3')
    canvas.pack_forget()
    
    global current_canvas
    
    if current_canvas:
        current_canvas.pack_forget()
        
    #canvasListSuburb.pack_forget()
    canvasCleanliness = Canvas(
    window,
    bg = "#E8E8E8",
    height = 626,
    width = 932,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
    )

    canvasCleanliness.place(x = 0, y = 0)
    canvasCleanliness.update()  # Update the canvas before getting dimensions
    print("Canvas dimensions:", canvasCleanliness.winfo_width(), canvasCleanliness.winfo_height())

    canvasCleanliness.create_rectangle(
    228.0,
    122.0,
    899.0,
    517.0,
    fill="#FFFFFF",
    outline="")

    canvasCleanliness.create_rectangle(
        0.0,
        0.0,
        195.0,
        626.0,
        fill="#32213A",
        outline="")
    
    entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
    window.eleven = entry_image_1
    entry_bg_1 = canvasCleanliness.create_image(
        563.5,
        474.5,
        image=entry_image_1
    )
    entry_1 = Entry(
        bd=0,
        bg="#E8E8E8",
        fg="#000716",
        highlightthickness=0
    )
    entry_1.place(
        x=446.0,
        y=455.0,
        width=235.0,
        height=37.0
    )

    image_image_1 = PhotoImage(
    file=relative_to_assets("display_chart_by_cleanliness.png"))
    window.twelve = image_image_1
    image_1 = canvasCleanliness.create_image(
    564.0,
    70.0,
    image=image_image_1
    )
    
    button_image_1 = PhotoImage(
        file=relative_to_assets("display_by_ratings.png"))
    window.three = button_image_1
    button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: show_canvas6(),
    relief="flat"
    )
    
    button_1.place(
        x=33.0,
        y=539.0,
        width=126.0,
        height=56.0
    )
    
    image_image_2 = PhotoImage(
    file=relative_to_assets("home.png"))
    window.thirteen = image_image_2
    image_2 = canvasCleanliness.create_image(
        96.0,
        145.0,
        image=image_image_2
    )

    button_image_1 = PhotoImage(
    file=relative_to_assets("display_by_ratings.png"))
    window.fourteen = button_image_1
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: show_canvas6(),
        relief="flat"
    )
    button_1.place(
        x=33.0,
        y=539.0,
        width=126.0,
        height=56.0
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets("price_chart.png"))
    window.fifteen = button_image_2
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: show_canvas4(),
        relief="flat"
    )
    button_2.place(
        x=33.0,
        y=302.0,
        width=126.0,
        height=56.0
    )

    button_image_3 = PhotoImage(
        file=relative_to_assets("cleanliness.png"))
    window.sixteen = button_image_3
    button_3 = Button(
        image=button_image_3,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_3 clicked"),
        relief="flat"
    )
    button_3.place(
        x=33.0,
        y=460.0,
        width=126.0,
        height=56.0
    )

    button_image_4 = PhotoImage(
        file=relative_to_assets("search.png"))
    window.seventeen = button_image_4
    button_4 = Button(
        image=button_image_4,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: show_canvas5(),
        relief="flat"
    )
    button_4.place(
        x=33.0,
        y=381.0,
        width=126.0,
        height=56.0
    )

    button_image_5 = PhotoImage(
        file=relative_to_assets("suburb_listing.png"))
    window.eighteen = button_image_5
    button_5 = Button(
        image=button_image_5,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: show_canvas2(),
        relief="flat"
    )
    button_5.place(
        x=33.0,
        y=223.0,
        width=126.0,
        height=56.0
    )

    canvasCleanliness.create_text(
        56.0,
        36.0,
        anchor="nw",
        text="AJJ",
        fill="#FFFFFF",
        font=("Inter Bold", 40 * -1)
    )
    
    button_image_5 = PhotoImage(
    file=relative_to_assets("display.png"))
    window.nineteen = button_image_5
    button_5 = Button(
        image=button_image_5,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_5 clicked"),
        relief="flat"
    )
    button_5.place(
        x=454.0,
        y=536.0,
        width=218.0,
        height=39.0
    )

    canvasCleanliness.pack()
    current_canvas = canvasCleanliness


#Display ratings listings
def show_canvas6():
    print("canvas 6")
    canvas.pack_forget()
    global current_canvas
    
    if current_canvas:
        current_canvas.pack_forget()
        
    canvasListingsByRatings = Canvas(
    window,
    bg = "#E8E8E8",
    height = 626,
    width = 932,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
    )

    canvasListingsByRatings.place(x = 0, y = 0)
    canvasListingsByRatings.update()  # Update the canvas before getting dimensions
    print("Canvas dimensions:", canvasListingsByRatings.winfo_width(), canvasListingsByRatings.winfo_height())

    canvasListingsByRatings.create_rectangle(
        228.0,
        122.0,
        899.0,
        517.0,
        fill="#FFFFFF",
        outline="")

    canvasListingsByRatings.create_rectangle(
        0.0,
        0.0,
        195.0,
        626.0,
        fill="#32213A",
        outline="")
    
    canvasListingsByRatings.create_rectangle(
    461.0,
    455.0,
    679.0,
    494.0,
    fill="#E8E8E8",
    outline="")
    
    image_image_6 = PhotoImage(
        file=relative_to_assets("home.png"))
    window.one = image_image_6
    # Create and place the image on canvasListingsByRatings
    image_6 = canvasListingsByRatings.create_image(
        96.0,
        145.0,
        image=image_image_6
    )

    button_image_1 = PhotoImage(
    file=relative_to_assets("display_list.png"))
    window.negativenegative = button_image_1
    button_111 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        relief="flat"
    )
    button_111.place(
        x=284.0,
        y=536.0,
        width=218.0,
        height=39.0
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets("display_chart.png"))
    window.negativenegativenegative = button_image_2
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: show_canvas7(),
        relief="flat"
    )
    button_2.place(
        x=626.0,
        y=536.0,
        width=218.0,
        height=39.0
    )


    image_image_1 = PhotoImage(
    file=relative_to_assets("display_listings_by_ratings_chart.png"))
    window.two = image_image_1
    image_1 = canvasListingsByRatings.create_image(
        564.0,
        70.0,
        image=image_image_1
    )
    
    canvasListingsByRatings.create_text(
    56.0,
    36.0,
    anchor="nw",
    text="AJJ",
    fill="#FFFFFF",
    font=("Inter Bold", 40 * -1)
    )

    
    entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
    window.three = entry_image_1
    entry_bg_1 = canvasListingsByRatings.create_image(
        563.5,
        474.5,
        image=entry_image_1
    )
    entry_1 = Entry(
        bd=0,
        bg="#E8E8E8",
        fg="#000716",
        highlightthickness=0
    )
    entry_1.place(
        x=446.0,
        y=455.0,
        width=235.0,
        height=37.0
    )
    
    button_image_1 = PhotoImage(
    file=relative_to_assets("display_by_ratings.png"))
    window.six = button_image_1
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: show_canvas6(),
        relief="flat"
    )
    button_1.place(
        x=33.0,
        y=539.0,
        width=126.0,
        height=56.0
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets("price_chart.png"))
    window.seven = button_image_2
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: show_canvas4(),
        relief="flat"
    )
    button_2.place(
        x=33.0,
        y=302.0,
        width=126.0,
        height=56.0
    )

    button_image_3 = PhotoImage(
        file=relative_to_assets("cleanliness.png"))
    window.eight = button_image_3
    button_3 = Button(
        image=button_image_3,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: show_canvas3(),
        relief="flat"
    )
    button_3.place(
        x=33.0,
        y=460.0,
        width=126.0,
        height=56.0
    )

    button_image_4 = PhotoImage(
        file=relative_to_assets("search.png"))
    window.nine = button_image_4
    button_4 = Button(
        image=button_image_4,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: show_canvas5(),
        relief="flat"
    )
    button_4.place(
        x=33.0,
        y=381.0,
        width=126.0,
        height=56.0
    )

    button_image_5 = PhotoImage(
        file=relative_to_assets("suburb_listing.png"))
    window.ten = button_image_5
    button_5 = Button(
        image=button_image_5,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: show_canvas2(),
        relief="flat"
    )
    button_5.place(
        x=33.0,
        y=223.0,
        width=126.0,
        height=56.0
    )

    canvasListingsByRatings.create_text(
        56.0,
        36.0,
        anchor="nw",
        text="AJJ",
        fill="#FFFFFF",
        font=("Inter Bold", 40 * -1)
    )

    canvasListingsByRatings.pack()
    current_canvas = canvasListingsByRatings
    
#Display ratings listings
def show_canvas7():
    canvas.pack_forget()
    global current_canvas
    
    if current_canvas:
        current_canvas.pack_forget()
        
    canvasListingsByRatingsChart = Canvas(
    window,
    bg = "#E8E8E8",
    height = 626,
    width = 932,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
    )

    canvasListingsByRatingsChart.place(x = 0, y = 0)
    canvasListingsByRatingsChart.update()  # Update the canvas before getting dimensions
    print("Canvas dimensions:", canvasListingsByRatingsChart.winfo_width(), canvasListingsByRatingsChart.winfo_height())

    canvasListingsByRatingsChart.create_rectangle(
        228.0,
        122.0,
        899.0,
        517.0,
        fill="#FFFFFF",
        outline="")

    canvasListingsByRatingsChart.create_rectangle(
        0.0,
        0.0,
        195.0,
        626.0,
        fill="#32213A",
        outline="")
    
    canvasListingsByRatingsChart.create_rectangle(
    461.0,
    455.0,
    679.0,
    494.0,
    fill="#E8E8E8",
    outline="")
    
    image_image_6 = PhotoImage(
        file=relative_to_assets("home.png"))
    window.one = image_image_6
    # Create and place the image on canvasListingsByRatingsChart
    image_6 = canvasListingsByRatingsChart.create_image(
        96.0,
        145.0,
        image=image_image_6
    )

    button_image_1 = PhotoImage(
    file=relative_to_assets("display_list.png"))
    window.negativenegative = button_image_1
    button_111 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: show_canvas6(),
        relief="flat"
    )
    button_111.place(
        x=284.0,
        y=536.0,
        width=218.0,
        height=39.0
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets("display_chart.png"))
    window.negativenegativenegative = button_image_2
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        relief="flat"
    )
    button_2.place(
        x=626.0,
        y=536.0,
        width=218.0,
        height=39.0
    )


    image_image_1 = PhotoImage(
    file=relative_to_assets("display_listings_by_ratings.png"))
    window.two = image_image_1
    image_1 = canvasListingsByRatingsChart.create_image(
        564.0,
        70.0,
        image=image_image_1
    )
    
    canvasListingsByRatingsChart.create_text(
    56.0,
    36.0,
    anchor="nw",
    text="AJJ",
    fill="#FFFFFF",
    font=("Inter Bold", 40 * -1)
    )

    
    entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
    window.three = entry_image_1
    entry_bg_1 = canvasListingsByRatingsChart.create_image(
        563.5,
        474.5,
        image=entry_image_1
    )
    entry_1 = Entry(
        bd=0,
        bg="#E8E8E8",
        fg="#000716",
        highlightthickness=0
    )
    entry_1.place(
        x=446.0,
        y=455.0,
        width=235.0,
        height=37.0
    )
    
    button_image_1 = PhotoImage(
    file=relative_to_assets("display_by_ratings.png"))
    window.six = button_image_1
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: show_canvas6(),
        relief="flat"
    )
    button_1.place(
        x=33.0,
        y=539.0,
        width=126.0,
        height=56.0
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets("price_chart.png"))
    window.seven = button_image_2
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: show_canvas4(),
        relief="flat"
    )
    button_2.place(
        x=33.0,
        y=302.0,
        width=126.0,
        height=56.0
    )

    button_image_3 = PhotoImage(
        file=relative_to_assets("cleanliness.png"))
    window.eight = button_image_3
    button_3 = Button(
        image=button_image_3,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: show_canvas3(),
        relief="flat"
    )
    button_3.place(
        x=33.0,
        y=460.0,
        width=126.0,
        height=56.0
    )

    button_image_4 = PhotoImage(
        file=relative_to_assets("search.png"))
    window.nine = button_image_4
    button_4 = Button(
        image=button_image_4,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: show_canvas5(),
        relief="flat"
    )
    button_4.place(
        x=33.0,
        y=381.0,
        width=126.0,
        height=56.0
    )

    button_image_5 = PhotoImage(
        file=relative_to_assets("suburb_listing.png"))
    window.ten = button_image_5
    button_5 = Button(
        image=button_image_5,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: show_canvas2(),
        relief="flat"
    )
    button_5.place(
        x=33.0,
        y=223.0,
        width=126.0,
        height=56.0
    )

    canvasListingsByRatingsChart.create_text(
        56.0,
        36.0,
        anchor="nw",
        text="AJJ",
        fill="#FFFFFF",
        font=("Inter Bold", 40 * -1)
    )

    canvasListingsByRatingsChart.pack()
    current_canvas = canvasListingsByRatingsChart

canvas = Canvas(
    window,
    bg = "#E8E8E8",
    height = 626,
    width = 932,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("welcome_img.png"))
image_1 = canvas.create_image(
    563.0,
    312.0,
    image=image_image_1
)

canvas.create_rectangle(
    0.0,
    0.0,
    195.0,
    626.0,
    fill="#32213A",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("display_by_ratings.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: show_canvas6(),
    relief="flat"
)
button_1.place(
    x=33.0,
    y=539.0,
    width=126.0,
    height=56.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("price_chart.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: show_canvas4(),
    relief="flat"
)
button_2.place(
    x=33.0,
    y=302.0,
    width=126.0,
    height=56.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("cleanliness.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: show_canvas3(),
    relief="flat"
)
button_3.place(
    x=33.0,
    y=460.0,
    width=126.0,
    height=56.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("search.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: show_canvas5(),
    relief="flat"
)
button_4.place(
    x=33.0,
    y=381.0,
    width=126.0,
    height=56.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("suburb_listing.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: show_canvas2(),
    relief="flat"
)
button_5.place(
    x=33.0,
    y=223.0,
    width=126.0,
    height=56.0
)

canvas.create_text(
    56.0,
    36.0,
    anchor="nw",
    text="AJJ",
    fill="#FFFFFF",
    font=("Inter Bold", 40 * -1)
)

image_image_2 = PhotoImage(
    file=relative_to_assets("home.png"))
image_2 = canvas.create_image(
    96.0,
    145.0,
    image=image_image_2
)

canvas.pack()

window.resizable(False, False)
window.mainloop()
